version: "3"

services:
  web1:
    image: nginx
    volumes:
      - ./web1:/usr/share/nginx/html/web1
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.web1.entrypoints=web
      - traefik.http.routers.web1.rule=PathPrefix(`/web1`)

  web2:
    image: nginx
    volumes:
      - ./web2:/usr/share/nginx/html
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.web2.entrypoints=web
      - traefik.http.routers.web2.rule=Host(`web2.localhost`)

networks:
  web:
    external:
      name: docker-mgr_web
